output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubectl_config
  sensitive   = true
}

output "ecr_hello_service_url" {
  description = "ECR repository URL for hello service"
  value       = aws_ecr_repository.hello_service.repository_url
}

output "ecr_profile_service_url" {
  description = "ECR repository URL for profile service"
  value       = aws_ecr_repository.profile_service.repository_url
}

output "ecr_frontend_url" {
  description = "ECR repository URL for frontend"
  value       = aws_ecr_repository.frontend.repository_url
}

output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}