apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: smple-mern
spec:
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: smple-mern
  labels:
    app: profile-service
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: profile-service