# Global configuration
global:
  namespace: sample-mern
  region: ap-south-1
  clusterName: my-eks-cluster
  imagePullSecrets: ecr-registry-secret

# Environment: minikube or eks
  environment: eks
 # Registry configuration
  registry:
    # For EKS
    eks:
      url: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/rikhrv
    # For Minikube - using local images
    minikube:
      url: ""  
# Autoscaling defaults
autoscaling:
  enabled: true
  default:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: "{{.Values.environment.eks.url}}/samplmernfrontend" #975050024946.dkr.ecr.ap-south-1.amazonaws.com/rikhrv/samplmernfrontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer # Set to "LoadBalancer" for EKS, change to "NodePort" for minikube if needed
    port: 3000
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  env:
    helloServiceUrl: "http://hello-service:3001"
    profileServiceUrl: "http://profile-service:3002"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

# Backend services configuration
backend:
  helloService:
    replicaCount: 1
    image:
      repository: "{{.Values.environment.eks.url}}/hello-service" #975050024946.dkr.ecr.ap-south-1.amazonaws.com/rikhrv/hello-service
      tag: latest
    service:
      type: LoadBalancer # Set to "LoadBalancer" for EKS, change to "ClusterIP" for minikube if needed
      port: 3001
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 250m
    port: 3001
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
  
  profileService:
    replicaCount: 1
    image:
      repository: "{{.Values.environment.eks.url}}/profile-service"    #975050024946.dkr.ecr.ap-south-1.amazonaws.com/rikhrv/profile-service
      tag: latest
    service:
      type: LoadBalancer # Set to "LoadBalancer" for EKS, change to "ClusterIP" for minikube if needed
      port: 3002
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 250m
    port: 3002
    mongoUri:
      secretName: mongo-secret
      secretKey: MONGO_URI
      value: uZ29kYitzcnY6Ly9tbmdhZG1pbjppdUMyMER2WW9yZlhLVGRTQGNsdXN0ZXIwLmkwcG92Lm1vbmdvZGIubmV0L3VzZXJkYg==
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      metrics:
      - type: External
        external:
          metric:
            name: nodes_count
            selector:
              matchLabels:
                service: profile-service
          target:
            type: AverageValue
            averageValue: 1
# ConfigMaps
configMaps:
  hello:
    port: "3001"
  profile:
    port: "3002"
# CloudWatch configuration
cloudwatch:
  enabled: true
  namespace: MERNApp
  logGroupName: /eks/mern-app-logs
  retentionInDays: 7
  serviceAccount:
    create: true
    name: cloudwatch-agent
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::975050024946:role/EKS-CloudWatch-Agent-Role