apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-config
  namespace: sample-mern
data:
  PORT: "3002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: sample-mern
data:
  PORT: "3001"
